# Generated by Django 3.2.9 on 2023-08-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='cliente id'),
        ),
    ]
