# Generated by Django 3.2.9 on 2023-08-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='teléfono'),
        ),
    ]
