# Generated by Django 3.2.9 on 2023-11-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_enterprise_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.CharField(max_length=64, null=True, verbose_name='ip_address'),
        ),
    ]
