# Generated by Django 4.1.10 on 2026-03-13 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalCodeEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_id', models.IntegerField(verbose_name='ID del Crédito')),
                ('approval_code', models.CharField(max_length=50, verbose_name='Código de Aprobación')),
                ('credit_value', models.CharField(max_length=50, verbose_name='Valor del Crédito')),
                ('email_to', models.EmailField(max_length=254, verbose_name='Correo Destino')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('success', models.BooleanField(default=True, verbose_name='Enviado Exitosamente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Correo - Código de Aprobación',
                'verbose_name_plural': 'Logs de Correos - Códigos de Aprobación',
                'ordering': ['-sent_at'],
            },
        ),
    ]
